-- MySQL Script generated by MySQL Workbench
-- Tue Oct 25 13:24:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_apotek_paramel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_apotek_paramel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_apotek_paramel` DEFAULT CHARACTER SET utf8mb4 ;
USE `db_apotek_paramel` ;

-- -----------------------------------------------------
-- Table `db_apotek_paramel`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_apotek_paramel`.`customers` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` LONGTEXT NULL DEFAULT NULL,
  `telephone` SMALLINT(6) NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_apotek_paramel`.`product_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_apotek_paramel`.`product_types` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_apotek_paramel`.`product_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_apotek_paramel`.`product_categories` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_type_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_categories_product_type_id_foreign` (`product_type_id` ASC) VISIBLE,
  CONSTRAINT `product_categories_product_type_id_foreign`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `db_apotek_paramel`.`product_types` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_apotek_paramel`.`product_uom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_apotek_paramel`.`product_uom` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_apotek_paramel`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_apotek_paramel`.`products` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_type_id` BIGINT(20) UNSIGNED NOT NULL,
  `product_category_id` BIGINT(20) UNSIGNED NOT NULL,
  `product_uom_id` BIGINT(20) UNSIGNED NOT NULL,
  `nama` VARCHAR(255) NOT NULL,
  `min_stock` DOUBLE NOT NULL,
  `diskon` DOUBLE NOT NULL,
  `keuntungan` DOUBLE NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `products_product_type_id_foreign` (`product_type_id` ASC) VISIBLE,
  INDEX `products_product_category_id_foreign` (`product_category_id` ASC) VISIBLE,
  INDEX `products_product_uom_id_foreign` (`product_uom_id` ASC) VISIBLE,
  CONSTRAINT `products_product_category_id_foreign`
    FOREIGN KEY (`product_category_id`)
    REFERENCES `db_apotek_paramel`.`product_categories` (`id`),
  CONSTRAINT `products_product_type_id_foreign`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `db_apotek_paramel`.`product_types` (`id`),
  CONSTRAINT `products_product_uom_id_foreign`
    FOREIGN KEY (`product_uom_id`)
    REFERENCES `db_apotek_paramel`.`product_uom` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_apotek_paramel`.`stock_opname`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_apotek_paramel`.`stock_opname` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `no_opname` VARCHAR(255) NOT NULL,
  `bulan` INT(11) NOT NULL,
  `tanggal_mulai` DATE NOT NULL,
  `tanggal_berakhir` DATE NOT NULL,
  `operator` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_apotek_paramel`.`detail_stock_opname`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_apotek_paramel`.`detail_stock_opname` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `stock_opname_id` BIGINT(20) UNSIGNED NOT NULL,
  `product_id` BIGINT(20) UNSIGNED NOT NULL,
  `stock_computer` DATETIME NOT NULL,
  `stock_aktual` INT(11) NOT NULL,
  `stock_selisih` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `detail_stock_opname_stock_opname_id_foreign` (`stock_opname_id` ASC) VISIBLE,
  INDEX `detail_stock_opname_product_id_foreign` (`product_id` ASC) VISIBLE,
  CONSTRAINT `detail_stock_opname_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_apotek_paramel`.`products` (`id`),
  CONSTRAINT `detail_stock_opname_stock_opname_id_foreign`
    FOREIGN KEY (`stock_opname_id`)
    REFERENCES `db_apotek_paramel`.`stock_opname` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_apotek_paramel`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_apotek_paramel`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_apotek_paramel`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_apotek_paramel`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_apotek_paramel`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_apotek_paramel`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_apotek_paramel`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_apotek_paramel`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_apotek_paramel`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_apotek_paramel`.`suppliers` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` LONGTEXT NULL DEFAULT NULL,
  `telephone` VARCHAR(255) NULL DEFAULT NULL,
  `bank_address` VARCHAR(255) NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_apotek_paramel`.`purchase_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_apotek_paramel`.`purchase_order` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `supplier_id` BIGINT(20) UNSIGNED NOT NULL,
  `employe_id` BIGINT(20) UNSIGNED NOT NULL,
  `no_transaction` VARCHAR(8) NOT NULL,
  `transaction_date` DATETIME NOT NULL,
  `payment_method` ENUM('Tunai', 'Kredit') NOT NULL,
  `tanggal_jatuh_tempo` DATETIME NOT NULL,
  `tanggal_pelunasan` DATETIME NOT NULL,
  `total` DOUBLE NOT NULL,
  `state` ENUM('Lunas', 'Belum Lunas', 'Draft') NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `purchase_order_supplier_id_foreign` (`supplier_id` ASC) VISIBLE,
  INDEX `purchase_order_employe_id_foreign` (`employe_id` ASC) VISIBLE,
  CONSTRAINT `purchase_order_employe_id_foreign`
    FOREIGN KEY (`employe_id`)
    REFERENCES `db_apotek_paramel`.`users` (`id`),
  CONSTRAINT `purchase_order_supplier_id_foreign`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `db_apotek_paramel`.`suppliers` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_apotek_paramel`.`sales_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_apotek_paramel`.`sales_order` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` BIGINT(20) UNSIGNED NOT NULL,
  `employee_id` BIGINT(20) UNSIGNED NOT NULL,
  `no_transaction` VARCHAR(8) NOT NULL,
  `transaction_date` DATETIME NOT NULL,
  `payment_method` ENUM('Cash', 'BPJS') NOT NULL,
  `no_bpjs` VARCHAR(255) NOT NULL,
  `total` DOUBLE NOT NULL,
  `state` ENUM('Lunas', 'Belum Lunas') NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `sales_order_customer_id_foreign` (`customer_id` ASC) VISIBLE,
  INDEX `sales_order_employee_id_foreign` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `sales_order_customer_id_foreign`
    FOREIGN KEY (`customer_id`)
    REFERENCES `db_apotek_paramel`.`customers` (`id`),
  CONSTRAINT `sales_order_employee_id_foreign`
    FOREIGN KEY (`employee_id`)
    REFERENCES `db_apotek_paramel`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_apotek_paramel`.`stock_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_apotek_paramel`.`stock_in` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `purchase_order_id` BIGINT(20) UNSIGNED NOT NULL,
  `product_id` BIGINT(20) UNSIGNED NOT NULL,
  `expired_date` DATETIME NOT NULL,
  `jumlah` INT(11) NOT NULL,
  `diskon` INT(11) NOT NULL,
  `harga` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `stock_in_purchase_order_id_foreign` (`purchase_order_id` ASC) VISIBLE,
  INDEX `stock_in_product_id_foreign` (`product_id` ASC) VISIBLE,
  CONSTRAINT `stock_in_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_apotek_paramel`.`products` (`id`),
  CONSTRAINT `stock_in_purchase_order_id_foreign`
    FOREIGN KEY (`purchase_order_id`)
    REFERENCES `db_apotek_paramel`.`purchase_order` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_apotek_paramel`.`stock_out`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_apotek_paramel`.`stock_out` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sales_order_id` BIGINT(20) UNSIGNED NOT NULL,
  `product_id` BIGINT(20) UNSIGNED NOT NULL,
  `jumlah` INT(11) NOT NULL,
  `keuntungan` INT(11) NOT NULL,
  `diskon` INT(11) NOT NULL,
  `harga` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `stock_out_sales_order_id_foreign` (`sales_order_id` ASC) VISIBLE,
  INDEX `stock_out_product_id_foreign` (`product_id` ASC) VISIBLE,
  CONSTRAINT `stock_out_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_apotek_paramel`.`products` (`id`),
  CONSTRAINT `stock_out_sales_order_id_foreign`
    FOREIGN KEY (`sales_order_id`)
    REFERENCES `db_apotek_paramel`.`sales_order` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `db_apotek_paramel` ;

-- -----------------------------------------------------
-- Placeholder table for view `db_apotek_paramel`.`get_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_apotek_paramel`.`get_product` (`id` INT, `product_type_id` INT, `product_category_id` INT, `product_uom_id` INT, `nama` INT, `min_stock` INT, `diskon` INT, `keuntungan` INT, `created_at` INT, `updated_at` INT, `category` INT, `type` INT, `uom` INT, `harga` INT);

-- -----------------------------------------------------
-- View `db_apotek_paramel`.`get_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_apotek_paramel`.`get_product`;
USE `db_apotek_paramel`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `db_apotek_paramel`.`get_product` AS select `p`.`id` AS `id`,`p`.`product_type_id` AS `product_type_id`,`p`.`product_category_id` AS `product_category_id`,`p`.`product_uom_id` AS `product_uom_id`,`p`.`nama` AS `nama`,`p`.`min_stock` AS `min_stock`,`p`.`diskon` AS `diskon`,`p`.`keuntungan` AS `keuntungan`,`p`.`created_at` AS `created_at`,`p`.`updated_at` AS `updated_at`,`c`.`name` AS `category`,`t`.`name` AS `type`,`u`.`name` AS `uom`,(select `s`.`harga` from `db_apotek_paramel`.`stock_in` `s` where `s`.`product_id` = `p`.`id` and `s`.`jumlah` > 0 order by `s`.`expired_date` <> 0 and `s`.`created_at` <> 0 desc limit 1) AS `harga` from (((`db_apotek_paramel`.`products` `p` join `db_apotek_paramel`.`product_categories` `c` on(`p`.`product_category_id` = `c`.`id`)) join `db_apotek_paramel`.`product_types` `t` on(`p`.`product_type_id` = `t`.`id`)) join `db_apotek_paramel`.`product_uom` `u` on(`p`.`product_uom_id` = `u`.`id`));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
